[JavaScript] Add gulp-istanbul sample project.
There is the below error.
Error: task completion callback called too many times

I did not get the reason yet.